#!/usr/bin/perl

use strict;
use CGI qw/:all/;
use CGI::Pretty;
use CGI::Carp 'fatalsToBrowser';
use Text::CSV;
use URI;

my @pwuid = getpwuid($<);
my $owner = $pwuid[0];
my $homedir = $pwuid[7];

my $docroot = $ENV{'DOCUMENT_ROOT'};
unless ($docroot) { $docroot = '/imports/www/math'; }

my $uri = URI->new($ENV{'REQUEST_URI'},'https');
my $path = $uri->path();
$path =~ s/%([0-9A-Fa-f]{2})/chr(hex($1))/eg;

# extract last path component of URI
# last component = seminar folder and also = seminar hashtag
# below filter out events not containing hashtag
$path =~ /\/([^\/]*?)\/$/;

# remove year if present
$path =~ s/\d\d\d\d\///;


my @navbar = get_folder($path); # relative to $docroot

#delete current=last year
#pop @navbar;

if ($ENV{'DOCUMENT_ROOT'}) { print header; }

print '<p>';
print  join ' | ',  map a({-href=>$path . $_},$_), @navbar; 
print'</p>';



#############################

sub getvalue {
	my $file = $_[0];
	return unless (-e $file);
	open FILE, '<', $file;
	my @lines = <FILE>;
	close FILE;
	return join '', @lines;
}


sub is_active {
        # $dir is relative to $docroot with leading and trailing /
        my $dir = $_[0];
        # if not, prepend and append /
        unless ($dir =~ /^\//) { $dir = '/' . $dir; }
        unless ($dir =~ /\/$/) { $dir .= '/'; }
        return unless (-d $docroot . $dir);
        return unless (-e $docroot . $dir . '.title');
        $dir =~ /^\/(.*?)\/$/;
        return $1;
}




sub get_order {
        # $dir is relative to $docroot without leading and trailing /
        my $dir = $_[0];
        # if not, remove leading and trailing /
        $dir =~ s/^\///;
        $dir =~ s/\/$//;
        my $order;
        return unless (-d $docroot . '/' . $dir);
        opendir DIR, $docroot . '/' . $dir;
        my @dirs = readdir DIR;
        closedir DIR;
        for (@dirs) {
                next if (/^\./);
                next unless (-d $docroot . '/' . $dir . '/' . $_);
                $order->{$_} = 1000;
        }
        return $order unless (-e $docroot . '/' . $dir . '/.order');
        open FILE, $docroot . '/' . $dir . '/.order';
        my @dirs = <FILE>;
        close FILE;
        chomp @dirs;
        for (0..$#dirs) { $order->{$dirs[$_]} = $_+1; }
        return $order;
}
                                                      

sub get_folder {
        # $dir is relative to $docroot without leading and trailing /
        my $dir = $_[0];
        # if not, remove leading and trailing /
        $dir =~ s/^\///;
        $dir =~ s/\/$//;
        return unless (-d $docroot . '/' . $dir);
        opendir DIR, $docroot . '/' . $dir;
        my @dirs = readdir DIR;
        closedir DIR;
        my @navbar;
        for (@dirs) {
                next if (/^\./);
		next unless (-d $docroot . '/' . $dir . '/' . $_);
		next unless (/^2\d\d\d$/);
                push @navbar, $_; 
        }
        return sort { $a <=> $b } @navbar;
}
